apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "marte-ms.name" . }}
    chart: {{ template "marte-ms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ range $i, $var := .Values.svcAnnotations -}}
    {{ $var.name }}: {{ $var.value | quote}}
    {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{ range $i, $var := .Values.service.ports -}}
  - name: {{ $var.name }}
    port: {{ $var.port }}
    targetPort: {{ $var.port }}
  {{ end }}
  selector:
    app: {{ template "marte-ms.name" . }}
    release: {{ .Release.Name }}
---